### ISSUE TITLE
DzVents and EBUSD .updateSetpoint()

### ISSUE THREAD

**Issue by rivertechnology** [guillaumezin/DomoticzEbusd#16]
Hi! 

Thanks for this plugin! It’s great to be able to read my EBUS values in Domoticz.  

From the GUI I can change my thermostat setpoint. Only when I try to change this setpoint with a DzVents script using: 'domoticz.devices(IDX).updateSetPoint(19). My log says 'Updating SetPoint device....' but nothing changed.  

Is it possible to use DzVents and this plugin?

Thanks in advance for the help!

**Comment by guillaumezin** [comment]
Hi,

This is supposed to work, but I should check before and I have no access to my computer for a few days. Which Domoticz and plug-in versions are you using?

**Comment by rivertechnology** [comment]
Hi, Thanks for your reply.
ebsud:version 1.4.5, author 'Barberousse'
domoticz: Version: 2024.7
dzVents: Version: 3.1.8

No rush, i'm happy that you will take time to have a look.

**Comment by guillaumezin** [comment]
Hello,
Could you test version 2.2.1?

**Comment by rivertechnology** [comment]
> Hello, Could you test version 2.2.1?

COOL!!! Works perfeclty. Thanks al lot.

Offtopic: Is it  possible to round at 1 digit the 'z1roomtemp' or is this a domoticz/ebusd issue?. All other EBUS sensors are at 1 digit.

**Comment by guillaumezin** [comment]
All my sensors use 2 digits, it depends on ebusd. For instance in ebusd config files, some temperature types are D2C meaning 2 digits, others are D1C meaning 1 digit. But for temperature, I could round everything to 1 digit, it would make more sense.

**Comment by guillaumezin** [comment]
Version 2.2.2 should round temperature by 1 digit.
